### ISSUE TITLE
Rename of this repository

### ISSUE THREAD

**Issue by ummahusla** [Banjerr/react-paper-css#9]
Currently, `papercss` org has different names for different projects. It's kinda weird and I guess we need to stick to one naming convention.

* `papercss` is going to be our base/core. 

From it, we can do stuff like

* `papercss-react` 
* `papercss-vue` 
* etcetc

Next step is demo projects

* `papercss-demo`
* `papercss-react-demo`
* `papercss-vue-demo`
* etcetc

![image](https://user-images.githubusercontent.com/2536096/33982874-1cf097e6-e0aa-11e7-8cfb-f25b0997c534.png)

Please rename it appropriately, I appreciate that it might cause the problems and broken links, but better to do it early than later when projects are going to scale.

**Comment by rhyneav** [comment]
I like the syntax of `papercss-<framework>`, just my two cents!

**Comment by ummahusla** [comment]
@rhyneav I'm glad you liked it because I like it as well 😃

**Comment by ummahusla** [comment]
@rhyneav So it seems like it's nearly a month since no actions. Sadly enough.

**Comment by rhyneav** [comment]
Oh oops, would you like me to go ahead and update the name to papercss-react?

**Comment by ummahusla** [comment]
@rhyneav Or you can give me a admin access, so I can carry on tinkering 🔨 To simplify things, I guess admin access will suit the most.

**Comment by rhyneav** [comment]
Sounds good! I renamed it and gave you admin access for any future endeavors.
